name: trs
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  collection: ^1.17.0
  dotenv: ^4.0.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  json_annotation: ^4.7.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lints: ^2.0.0
  test: ^1.16.0
