version: '3'

tasks:
  serve: dart lib/main.dart serve --host localhost --port 8000
  tunnel: tunnelto -p 8000 -s trs
  watch: npx -y nodemon -w lib -e 'dart' -x 'task serve'
  run: dart lib/main.dart {{ .CLI_ARGS }}
  db:read: cat db.json | jq
  db:clear: rm db.json